val splits = bankingDF.randomSplit(Array(0.7,0.3))
val train = splits(0)
val test = splits(1)
val train_rows = train.count()
val test_rows = test.count()
printIn("Training Rows:" + train_rows + " Testing Rows:" + test_rows)